apiVersion: v1
kind: Namespace
metadata:
  name: stage1-newdevtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage1-newdevtest-app
  namespace: stage1-newdevtest
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: preprod-private
      containers:
      - name: frontend
        image: sathish8329/stage1-newdevtest:1118
        ports:
        - containerPort: 8081
        # Modified probes with increased timeouts and initial delay
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 90
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        # Add startup probe to give application time to fully initialize
        startupProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 15
          failureThreshold: 12  # Allows up to 3 minutes (12 * 15s) for startup
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        imagePullPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: stage1-newdevtest-frontend-service
  namespace: stage1-newdevtest
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # External port exposed for the service
      targetPort: 8081   # Matches the container port in the deployment
  type: NodePort        # Optional: Depending on your needs, you may choose ClusterIP or LoadBalancer instead
